import { ArrowUpRight, BarChart3, Check, ChevronRight, Clock3, Dumbbell, Filter, LockKeyhole, Search, Settings2, ShieldCheck, Trophy, Users } from "lucide-react";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/session";
import { NewExerciseForm, NewProgramForm } from "@/components/admin-forms";

type PageKind = "workouts" | "exercises" | "progress" | "history" | "profile" | "settings" | "admin" | "admin-workouts" | "admin-exercises";

const workouts = [
  ["Foundation full body", "Beginner · 30 min · No equipment", "Full body", "coral", "strength-foundations-full-body"],
  ["Upper body strength", "Intermediate · 42 min · Full gym", "Chest + back", "blue", "strength-foundations-upper"],
  ["Lower body power", "Intermediate · 48 min · Full gym", "Legs + glutes", "yellow", "strength-foundations-lower"],
  ["Conditioning circuit", "Advanced · 35 min · Home equipment", "Full body", "green", "strength-foundations-conditioning"],
];
const exercises = ["Barbell bench press", "Goblet squat", "Lat pulldown", "Romanian deadlift", "Dumbbell shoulder press", "Plank shoulder tap"];

export async function SectionPage({ kind, searchParams = {} }: { kind: PageKind; searchParams?: Record<string, string | undefined> }) {
  return <AppShell><div className="route-page">{kind === "workouts" && <WorkoutLibrary />}{kind === "exercises" && <ExerciseLibrary searchParams={searchParams} />}{kind === "progress" && <ProgressPage />}{kind === "history" && <HistoryPage />}{kind === "profile" && <ProfilePage />}{kind === "settings" && <SettingsPage />}{kind === "admin" && <AdminPage />}{kind === "admin-workouts" && <AdminWorkouts />}{kind === "admin-exercises" && <AdminExercises />}</div></AppShell>;
}

function PageHeader({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: React.ReactNode }) { return <header className="route-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{copy}</p></div>{action}</header>; }
async function WorkoutLibrary() { const databaseWorkouts = await prisma.workout.findMany({ where: { program: { published: true } }, include: { program: true, exercises: true }, orderBy: { name: "asc" } }); const cards = databaseWorkouts.length ? databaseWorkouts.map((workout, index) => [workout.name, `${workout.program?.difficulty ?? "BEGINNER"} · ${workout.duration} min · ${workout.program?.equipment ?? "No equipment"}`, `${workout.exercises.length} exercises`, ["coral", "blue", "yellow", "green"][index % 4], workout.slug]) : workouts; return <><PageHeader eyebrow="Training library" title="Choose your workout." copy="Structured sessions for wherever you are in your training." action={<button className="button button-primary"><Filter size={16} /> Filters</button>} /><div className="filter-row"><span className="filter-chip selected">All workouts</span><span className="filter-chip">Build strength</span><span className="filter-chip">Lose weight</span><span className="filter-chip">Improve endurance</span></div><div className="library-grid">{cards.map(([name, detail, muscle, color, slug]) => <Link className="library-card" href={`/workouts/${slug}`} key={name}><div className={`library-art ${color}`}><Dumbbell size={30} strokeWidth={1.4} /><span>{muscle}</span></div><div className="library-card-body"><h2>{name}</h2><p>{detail}</p><span className="text-link">View workout <ArrowUpRight size={14} /></span></div></Link>)}</div></>; }
async function ExerciseLibrary({ searchParams }: { searchParams: Record<string, string | undefined> }) { const query = searchParams.q?.trim(); const muscle = searchParams.muscle?.trim(); const type = searchParams.type?.trim(); const databaseExercises = await prisma.exercise.findMany({ where: { ...(query ? { OR: [{ name: { contains: query } }, { primaryMuscle: { contains: query } }, { equipment: { contains: query } }] } : {}), ...(muscle ? { primaryMuscle: muscle } : {}), ...(type ? { type: type as "STRENGTH" | "BODYWEIGHT" | "CARDIO" | "STRETCHING" | "MOBILITY" } : {}) }, orderBy: { name: "asc" }, take: 40 }); const rows = databaseExercises.length ? databaseExercises : exercises.map((name) => ({ name, primaryMuscle: "Full body", type: "STRENGTH" })); return <><PageHeader eyebrow="Movement library" title="Find your movement." copy="Explore exercises by muscle group, equipment, and level." /><form className="search-field" method="get"><Search size={18} /><input aria-label="Search exercises" defaultValue={query} name="q" placeholder="Search by name, muscle, or equipment" /><button className="search-submit" type="submit">Search</button></form><div className="filter-row"><Link className={`filter-chip ${!type ? "selected" : ""}`} href="/exercises">All</Link><Link className={`filter-chip ${type === "STRENGTH" ? "selected" : ""}`} href="/exercises?type=STRENGTH">Strength</Link><Link className={`filter-chip ${type === "BODYWEIGHT" ? "selected" : ""}`} href="/exercises?type=BODYWEIGHT">Bodyweight</Link><Link className={`filter-chip ${type === "MOBILITY" ? "selected" : ""}`} href="/exercises?type=MOBILITY">Mobility</Link></div><div className="exercise-list">{rows.map((exercise, index) => <Link className="exercise-row" href={`/exercises/${"slug" in exercise ? exercise.slug : "barbell-bench-press"}`} key={exercise.name}><div className={`exercise-icon tone-${index % 3}`}><Dumbbell size={18} /></div><div><h2>{exercise.name}</h2><p>{exercise.primaryMuscle} · {exercise.type.toLowerCase()}</p></div><ChevronRight size={18} /></Link>)}</div>{!rows.length && <div className="empty-note"><Search size={18} /> No exercises match those filters.</div>}</>; }
async function ProgressPage() { const user = await getCurrentUser(); const sessions = user ? await prisma.workoutSession.findMany({ where: { userId: user.id, completedAt: { not: null } }, include: { exercises: { include: { sets: true, exercise: true } } }, orderBy: { completedAt: "desc" } }) : []; const volume = sessions.reduce((total, session) => total + session.exercises.reduce((exerciseTotal, exercise) => exerciseTotal + exercise.sets.reduce((setTotal, set) => setTotal + (set.weight ?? 0) * (set.reps ?? 0), 0), 0), 0); const latestWeight = sessions[0]?.exercises[0]?.sets[0]?.weight; return <><PageHeader eyebrow="Your progress" title="Proof of the work." copy="See how your training is adding up over time." action={<Link className="button button-outline" href="/history"><Clock3 size={16} /> View history</Link>} /><div className="metric-grid"><Metric label="Workouts completed" value={String(sessions.length)} detail="completed sessions" /><Metric label="Total volume" value={`${Math.round(volume).toLocaleString()}`} detail="kg moved" /><Metric label="Latest logged weight" value={latestWeight ? `${latestWeight}` : "—"} detail={latestWeight ? "kg" : "Log a set to begin"} /></div><div className="progress-panel"><div className="section-heading"><div><p className="eyebrow">Strength trend</p><h2>Training activity</h2></div><span className="filter-chip selected">All time</span></div><div className="big-chart"><span className="chart-value">{sessions.length ? `${sessions.length} sessions` : "No sessions yet"}</span><div className="chart-line" /><div className="chart-dots"><i /><i /><i /><i /><i /><i /></div></div><div className="chart-labels"><span>Start</span><span>Week 2</span><span>Week 4</span><span>Today</span></div></div>{sessions.length === 0 && <div className="empty-note"><Trophy size={18} /> Personal records will appear here after your first completed workout.</div>}</>; }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="metric-card"><p className="eyebrow">{label}</p><strong>{value}</strong><span>{detail}</span></article>; }
async function HistoryPage() { const user = await getCurrentUser(); const sessions = user ? await prisma.workoutSession.findMany({ where: { userId: user.id, completedAt: { not: null } }, include: { workout: true, exercises: { include: { sets: true } } }, orderBy: { completedAt: "desc" } }) : []; return <><PageHeader eyebrow="Training log" title="Your history." copy="Every session is a marker of the work you put in." /><div className="history-list">{sessions.map((session) => <Link href={`/workouts/${session.workout.slug}`} className="history-row" key={session.id}><div className="history-date"><strong>{session.completedAt?.getDate()}</strong><span>{session.completedAt?.toLocaleString("en-US", { month: "short" }).toUpperCase()}</span></div><div className="history-copy"><h2>{session.workout.name}</h2><p>{session.exercises.length} exercises · {session.durationSeconds ? Math.round(session.durationSeconds / 60) : "—"} min</p></div><span className="record-badge"><Check size={13} /> Complete</span><ChevronRight size={18} /></Link>)}</div>{sessions.length === 0 && <div className="empty-note"><Clock3 size={18} /> Completed workouts will appear here after your first session.</div>}</>; }
function ProfilePage() { return <><PageHeader eyebrow="Your profile" title="Know your why." copy="Keep your goals close and your plan personal." /><div className="profile-layout"><div className="profile-summary panel"><div className="profile-avatar">AM</div><h2>Alex Morgan</h2><p>Training for strength · Intermediate</p><button className="button button-outline">Edit profile <Settings2 size={15} /></button></div><div className="profile-details panel"><p className="eyebrow">Training preferences</p>{[["Primary goal", "Build strength"], ["Weekly frequency", "4 workouts"], ["Preferred duration", "30–45 min"], ["Equipment", "Full gym"]].map(([label, value]) => <div className="detail-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div></>; }
function SettingsPage() { return <><PageHeader eyebrow="Preferences" title="Make it yours." copy="Control your reminders, account, and app preferences." /><div className="settings-list">{[["Workout reminders", "Get a nudge on your training days", true], ["Weekly summary", "See your progress every Sunday", true], ["Reduced motion", "Use fewer animations throughout the app", false]].map(([label, detail, checked]) => <div className="setting-row" key={String(label)}><div><h2>{label}</h2><p>{detail}</p></div><div className={`toggle ${checked ? "on" : ""}`} role="switch" aria-checked={Boolean(checked)} tabIndex={0}><span /></div></div>)}</div><div className="danger-zone"><LockKeyhole size={18} /><div><h2>Account security</h2><p>Password and session controls will live here.</p></div><ChevronRight size={18} /></div></>; }
function AdminPage() { return <><PageHeader eyebrow="Admin workspace" title="Keep the library strong." copy="Manage the content your members use to train." /><div className="admin-grid"><Link href="/admin/exercises" className="admin-card"><Dumbbell /><div><h2>Exercises</h2><p>Create and curate movement content.</p></div><ArrowUpRight /></Link><Link href="/admin/workouts" className="admin-card"><BarChart3 /><div><h2>Programs & workouts</h2><p>Build and publish structured plans.</p></div><ArrowUpRight /></Link><div className="admin-card"><Users /><div><h2>Members</h2><p>View active members and access.</p></div><span className="filter-chip">Soon</span></div></div><div className="admin-notice"><ShieldCheck size={18} /><span>Admin actions are protected on the server.</span></div></>; }
function AdminWorkouts() { return <><PageHeader eyebrow="Admin · Programs" title="Programs & workouts" copy="Create sessions members can follow." /><div className="admin-table">{["Beginner muscle building", "Strength foundations", "Conditioning essentials"].map((name, index) => <div className="admin-table-row" key={name}><div><h2>{name}</h2><p>{index + 3} workouts · {index + 4} weeks</p></div><span className="status-tag">Published</span><ChevronRight size={17} /></div>)}</div><NewProgramForm /></>; }
function AdminExercises() { return <><PageHeader eyebrow="Admin · Exercises" title="Exercise library" copy="Keep movement instructions clear and useful." /><div className="admin-table">{exercises.slice(0, 4).map((name) => <div className="admin-table-row" key={name}><div><h2>{name}</h2><p>Strength · Full gym · Intermediate</p></div><button className="icon-link" aria-label={`Edit ${name}`}><Settings2 size={16} /></button></div>)}</div><NewExerciseForm /></>; }
